# Generated by Django 5.1.2 on 2024-12-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='allowed_time_range_end',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='allowed_time_range_start',
        ),
    ]
